# general information

site_name: CrossFire & VMWare
site_description: Setup instructions to run CrossFire on a Virtual Machine using VMWare.
site_author: PDDStudio & Contributors
site_url: 'https://cfna.github.io/vmware-docs'

repo_name: 'vmware-docs'
repo_url: 'https://github.com/cfna/vmware-docs'

copyright: 'Copyright &copy; 2020 PDDStudio & Contributors'

# confiture build behavior
docs_dir: pages/
site_dir: build/
extra_javascript: 
  - js/extra.js

# customizing theme & plugins
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'green'
    accent: 'green'
  icon:
    logo: material/book-open-variant
    repo: material/git

extra:
  manifest: webapp.manifest
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cfna

# page navigation tree
nav:
  - Home: index.md
  - Welcome: welcome.md
  - Getting Started: getting_started.md
  - VMWare Guides:
    - Creating a Virtual Machine: vmware/creating_virtual_machine.md
    - Updating Virtual Machine Config: vmware/vm_configuration.md
    - Windows Registry Patch for Virtual Machines: vmware/registry_patch.md
  - CrossFire Guides:
    - AFK Bot & Auto Ready Setup Instructions: crossfire/vm_afk_bot_instructions.md
  - Video Guides: video_guides.md
  - Tested Versions: supported_versions.md


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all